wandb_version: 1

min_samples_leaf:
  desc: null
  value: 7
max_depth:
  desc: null
  value: 8
min_samples_split:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.2
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706079512.636281
    t:
      1:
      - 5
      - 35
      - 53
      - 55
      - 105
      2:
      - 5
      - 35
      - 53
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.16.2
      8:
      - 1
      - 5
      13: linux-x86_64
