wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.2
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706152698.081314
    t:
      1:
      - 5
      - 35
      - 53
      - 55
      - 105
      2:
      - 5
      - 35
      - 53
      - 55
      - 105
      3:
      - 2
      - 17
      - 18
      - 23
      - 37
      4: 3.10.12
      5: 0.16.2
      8:
      - 1
      - 5
      13: linux-x86_64
direction:
  desc: null
  value:
  - MAXIMIZE
min_samples_leaf:
  desc: null
  value: 3
max_depth:
  desc: null
  value: 5
min_samples_split:
  desc: null
  value: 10
