wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.2
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706154411.181205
    t:
      1:
      - 5
      - 35
      - 53
      - 55
      - 105
      2:
      - 5
      - 35
      - 53
      - 55
      - 105
      3:
      - 2
      - 23
      4: 3.10.12
      5: 0.16.2
      8:
      - 1
      - 5
      13: linux-x86_64
